apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightning-prometheus-exporter.fullname" . }}-creds
data:
  tls.cert: {{ .Values.secret.lndBase64Cert }}
  readonly.macaroon: {{ .Values.secret.lndBase64Macaroon }}
